export const TOGGLE_CURRENCIES_LOADING_STATUS =
  'TOGGLE_CURRENCIES_LOADING_STATUS';
export const CURRENCIES_LOAD_SUCCESS = 'CURRENCIES_LOAD_SUCCESS';
export const CURRENCIES_LOAD_ERROR = 'CURRENCIES_LOAD_ERROR';
export const TOGGLE_PLACES_LOADING_STATUS =
  'TOGGLE_PLACES_LOADING_STATUS';
export const PLACES_LOAD_SUCCESS = 'PLACES_LOAD_SUCCESS';
export const PLACES_LOAD_ERROR = 'PLACES_LOAD_ERROR';
export const TOGGLE_RESULTS_LOADING_STATUS = 'TOGGLE_RESULTS_LOADING_STATUS';
export const RESULTS_LOAD_SUCCESS = 'RESULTS_LOAD_SUCCESS';
export const RESULTS_LOAD_ERROR = 'RESULTS_LOAD_ERROR';
